before_install:
  - sudo rm -f /etc/mavenrc
  - export M2_HOME=/usr/local/maven
  - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m"
  - export HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE=false
jdk:
 - oraclejdk8
language: java
sudo: required
services:
  - docker

jobs:
  include:
    - stage: verify
      script: mvn clean verify -Ddockerfile.skip=false -DblackBoxTests.skip=false -DblackBoxTests.skipTailChildContainers=true
    - stage: push
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - mvn -DblackBoxTests.skip=true -DskipTests=true -Ddockerfile.skip=false -Ddocker.repo=ascentiotech -Ppush-docker-image install

stages:
  - verify
  - name: push
    if: branch = master

